image alice blush = "images/alice/blush.png"
image alice doubt = "images/alice/doubt.png"
image alice embarrassed = "images/alice/embarrassed.png"
image alice happy = "images/alice/happy.png"
image alice idle = "images/alice/idle.png"
image alice teasing = "images/alice/teasing.png"
image alice worried = "images/alice/worried.png"

image hunger normal = "images/hunger/normal.png"
image hunger normal shy = "images/hunger/normal_shy.png"
image hunger angry = "images/hunger/angry.png"
image hunger dissapointed = "images/hunger/dissapointed.png"
image hunger fear = "images/hunger/fear.png"
image hunger fear shy = "images/hunger/fear_shy.png"
image hunger laughing = "images/hunger/laughing.png"
image hunger laughing nervous = "images/hunger/laughing_nervous.png"
image hunger laughing nervous shy = "images/hunger/laughing_nervous_shy.png"
image hunger empty = "images/empty.png"

image war back = "images/war/war_back.png"
image war headsup = "images/war/war_headsup.png"
image war normal = "images/war/war_normal.png"
image war point = "images/war/war_point.png"
image war point angry = "images/war/war_pointangry.png"
image war stare = "images/war/war_stare.png"
image war empty = "images/empty.png"

image plague normal = "images/plague/conq_normal.png"
image plague normalsig = "images/plague/conq_normalsig.png"
image plague cinema = "images/plague/conq_cinema.png"
image plague cinemasig = "images/plague/conq_cinemasig.png"
image plague happy = "images/plague/conq_happy.png"
image plague happysig = "images/plague/conq_happysig.png"
image plague nervous = "images/plague/conq_nervous.png"
image plague nervoussig = "images/plague/conq_nervoussig.png"
image plague serious = "images/plague/conq_serious.png"
image plague serioussig = "images/plague/conq_serioussig.png"
image plague sad = "images/plague/conq_sad.png"
image plague sadsig = "images/plague/conq_sadsig.png"
image plague empty = "images/empty.png"


image bg city = "images/background/city.png"
image bg office = "images/background/office.png"
image bg darkness = "images/background/darkness.png"
image bg god = "images/background/god.png"
image bg cgall = "images/background/cgall.png"
image bg gate = "images/background/gate.png"
image bg diner = "images/background/diner.png"
image bg waroff = "images/background/waroff.png"
image bg dumpster = "images/background/dumpster.png"
image bg gpt = "images/background/gpt.png"
image bg corridor = "images/background/corridor.png"

image bg hungerend = "images/background/hungerend.png"
image bg warend = "images/background/warend.png"
image bg plagueend = "images/background/plagueend.png"
image bg warhungerend = "images/background/warhungerend.png"
image bg warplagueend = "images/background/warplagueend.png"
image bg plaguehunger = "images/background/plaguehungerend.png"
image bg allend = "images/background/allend.png"
image bg badend = "images/background/badend.png"