image alice blush = "images/alice/blush.png"
image alice doubt = "images/alice/doubt.png"
image alice embarrassed = "images/alice/embarrassed.png"
image alice happy = "images/alice/happy.png"
image alice idle = "images/alice/idle.png"
image alice teasing = "images/alice/teasing.png"
image alice worried = "images/alice/worried.png"

image hunger normal = "images/hunger/normal.png"
image hunger normal shy = "images/hunger/normal_shy.png"
image hunger angry = "images/hunger/angry.png"
image hunger dissapointed = "images/hunger/disappointed.png"
image hunger fear = "images/hunger/fear.png"
image hunger fear shy = "images/hunger/fear_shy.png"
image hunger laughing = "images/hunger/laughing.png"
image hunger laughing nervous = "images/hunger/laughing_nervous.png"
image hunger laughing nervous shy = "images/hunger/laughing_nervous_shy.png"

image bg city = "images/background/city.png"
image bg office = "images/background/office.png"
image bg darkness = "images/background/darkness.png"
image bg god = "images/background/god.png"
image bg cgall = "images/background/cgall.png"
image bg gate = "images/background/gate.png"
image bg diner = "images/background/diner.png"
image bg waroff = "images/background/waroff.png"
image bg dumpster = "images/background/dumpster.png"
image bg gpt = "images/background/gpt.png"