image alice blush = "images/alice/blush.png"
image alice doubt = "images/alice/doubt.png"
image alice embarrassed = "images/alice/embarrassed.png"
image alice happy = "images/alice/happy.png"
image alice idle = "images/alice/idle.png"
image alice teasing = "images/alice/teasing.png"
image alice worried = "images/alice/worried.png"

image bg city = "images/background/city.png"
image bg office = "images/background/office.png"
image bg darkness = "images/background/darkness.png"
image bg god = "images/background/god.png"
image bg cgall = "images/background/cgall.png"
image bg gate = "images/background/gate.png"
image bg diner = "images/background/diner.png"